language: python
python:
    - 2.6
    - 2.7
env:
    - DJANGO_VERSION=1.4.3
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - make install
script:
    - make report
after_script:
    - if [ $TRAVIS_PYTHON_VERSION == "2.7" ]; then
      pip install --quiet --use-mirrors coveralls
      coveralls;
      fi
