language: python
python:
    - 2.6
    - 2.7
env:
    - DJANGO_VERSION=1.4.3
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - make install
script:
    - make test
    - make report
    - make flake8
