language: python
python:
    - TOXENV=py26-django14
    - TOXENV=py26-django15
    - TOXENV=py27-django14
    - TOXENV=py27-django15
    - TOXENV=py32-django15
    - TOXENV=py33-django15
    - TOXENV=pypy-django14
    - TOXENV=pypy-django15
    - TOXENV=cov
matrix:
    allow_failures:
        - env: TOXENV=cov
install:
    - pip install --quiet --use-mirrors tox
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet --use-mirrors coveralls;
      coveralls;
      fi
